version: "3.9"

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.3
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__WEBSERVER__SECRET_KEY: "super_secret_replace_me"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT: 90
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres/airflow"
    _PIP_ADDITIONAL_REQUIREMENTS: "pandas requests pyarrow"
    SOURCE_URL: "https://wfs-kbhkort.kk.dk/k101/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=k101:trafiktaelling&outputFormat=CSV&SRSNAME=EPSG:4326"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    redis:
      condition: service_started
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5
    volumes:
      - ./_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  airflow-init:
    <<: *airflow-common
    command: ["bash", "-c", "airflow db init && airflow users create -u airflow -p airflow -r Admin -e admin@example.com -f Admin -l User"]

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      retries: 10

  spark-master:
    container_name: spark-master
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_WEBUI_PORT=8081
      - SPARK_MASTER_OPTS=-Dspark.master.ui.port=8081
    volumes:
      - ./jobs:/opt/spark/jobs
      - ./data:/data
    ports:
      - "7077:7077"
      - "8081:8081"

  spark-worker:
    container_name: spark-worker
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    volumes:
      - ./jobs:/opt/spark/jobs
      - ./data:/data
    depends_on:
      - spark-master

  streamlit:
    image: python:3.11-slim
    container_name: streamlit
    working_dir: /app
    command: bash -c "pip install streamlit pandas pyarrow plotly numpy && streamlit run app/streamlit_app.py --server.port=8501 --server.address=0.0.0.0"
    volumes:
      - ./app:/app/app
      - ./data:/data
    ports:
      - "8501:8501"
    depends_on:
      - spark-master

  scheduler:
    <<: *airflow-common
    command: scheduler
